[package]
name = "dig-rs"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.70"
bytes = "1.10.1"
clap = { version = "4.5.40", features = ["derive"] }
deku = "0.19.1"
env_logger = "0.11.8"
log = "0.4.27"
rand = "0.9.1"

[lints.rust]
unsafe_code = "forbid"
